python file my project, 15-20 min of work
Модель: Флэт

Для реализации этой модели я зануляю $\mu$ и уменьшаю $\sigma$, чтобы график вёл себя менее волатильно
Traceback (most recent call last):
  File "/home/roman/Documents/python/uniswap/Samoilov_Roman_final_project_short.py", line 1592, in <module>
    plt.plot(trajectories['datetime'], trajectories[column_name], label=f'Trajectory {i + 1}', color='blue', linewidth=1, alpha=0.5)
  File "/home/roman/.local/lib/python3.10/site-packages/matplotlib/pyplot.py", line 3019, in plot
    return gca().plot(
  File "/home/roman/.local/lib/python3.10/site-packages/matplotlib/axes/_axes.py", line 1605, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]
  File "/home/roman/.local/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 315, in __call__
    yield from self._plot_args(this, kwargs)
  File "/home/roman/.local/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 490, in _plot_args
    x = _check_1d(xy[0])
  File "/home/roman/.local/lib/python3.10/site-packages/matplotlib/cbook/__init__.py", line 1362, in _check_1d
    ndim = x[:, None].ndim
  File "/home/roman/.local/lib/python3.10/site-packages/pandas/core/series.py", line 1072, in __getitem__
    return self._get_with(key)
  File "/home/roman/.local/lib/python3.10/site-packages/pandas/core/series.py", line 1082, in _get_with
    return self._get_values_tuple(key)
  File "/home/roman/.local/lib/python3.10/site-packages/pandas/core/series.py", line 1122, in _get_values_tuple
    disallow_ndim_indexing(result)
  File "/home/roman/.local/lib/python3.10/site-packages/pandas/core/indexers/utils.py", line 341, in disallow_ndim_indexing
    raise ValueError(
ValueError: Multi-dimensional indexing (e.g. `obj[:, None]`) is no longer supported. Convert to a numpy array before indexing instead.